package input

import (
	"image"
	"math/rand"

	"gonum.org/v1/gonum/mat"
)

// returns a 2 dimensional sample set generated by the image
// or nil if the image cound not be processed or does not exist
//
// the image is the negative image of the ImageToSampleSet() function
func ImageToSampleSetReverse(imagePath string, setSample func(x, y int, img *image.Image) bool) []*mat.VecDense {

	var img *image.Image = GetImage(imagePath)
	if img == nil {
		return nil
	}
	var samples []*mat.VecDense

	boundsX := (*img).Bounds().Dx()
	boundsY := (*img).Bounds().Dy()

	for x := range boundsX {
		for y := range boundsY {

			if setSample(x, y, img) {
				samples = append(samples, mat.NewVecDense(2, []float64{float64(x) / float64(boundsX), 1.0 - float64(y)/float64(boundsY)}))
			}
		}
	}

	return samples
}

// returns a 2 dimensional sample set generated by the image
// or nil if the image cound not be processed or does not exist
func ImageToSampleSet(imagePath string) []*mat.VecDense {

	var img *image.Image = GetImage(imagePath)
	if img == nil {
		return nil
	}
	var samples []*mat.VecDense

	boundsX := (*img).Bounds().Dx()
	boundsY := (*img).Bounds().Dy()

	for x := range boundsX {
		for y := range boundsY {
			r, _, _, a := (*img).At(x, y).RGBA()
			if rand.Float64() < float64(r)/float64(0xffff)*float64(a)/float64(0xffff) {
				samples = append(samples, mat.NewVecDense(2, []float64{float64(x) / float64(boundsX), 1.0 - float64(y)/float64(boundsY)}))
			}
		}
	}

	return samples
}
